name: Python App CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.copydigest.outputs.digest }}
      
    steps:
    - name: Checkout the current application git repository
      uses: actions/checkout@v3

    - name: Login to the container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: quay.io
        username: ${{secrets.QUAY_LOGIN}}
        password: ${{secrets.QUAY_TOKEN}}

    - name: Build and push container image for the application
      id: build
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        push: true
        tags: quay.io/${{vars.QUAY_REPO}}/${{vars.IMAGE_NAME}}
        
    - name: Print the new image digest of the image
      run: echo ${{ steps.build.outputs.digest }}
      
    - name: Copy image digest to the job output
      id: copydigest
      run: echo "digest=${{ steps.build.outputs.digest }}" >> "$GITHUB_OUTPUT"

  deploy-in-dev:
    runs-on: ubuntu-latest
    environment: development
    needs: build
    steps:
    
    - name: Clone application gitops repository and update with new image digest
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git clone https://user:$GH_TOKEN@github.com/${{vars.APP_GITOPS_REPO}}

        cd python-basic-gitops/environment/dev
        git config user.name "ciuser"
        git config user.email "ciuser@gha.com"

        sed -i "s/digest:.*/digest: ${{needs.build.outputs.digest}}/g" ./kustomization.yaml
        git add .
        git commit -m "Updated image digest"
        git push -u origin master
    
    - name: Log in to OpenShift 
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{secrets.OPENSHIFT_SERVER}}
        openshift_token: ${{secrets.OPENSHIFT_TOKEN}}
        insecure_skip_tls_verify: true

    - name: Deploy gitops application in ArgoCD
      run: |
        cd sample-python-basic-gitops/argo
        oc apply -f application-dev.yaml -n openshift-gitops
        
  deploy-in-staging:
    runs-on: ubuntu-latest
    environment: staging
    needs: [build,deploy-in-dev]
    steps:
    
    - name: Clone application gitops repository and update with new image digest
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
      
        git clone https://user:$GH_TOKEN@github.com/${{vars.APP_GITOPS_REPO}}

        cd python-basic-gitops/environment/staging
        git config user.name "ciuser"
        git config user.email "ciuser@gha.com"

        sed -i "s/digest:.*/digest: ${{needs.build.outputs.digest}}/g" ./kustomization.yaml
        git add .
        git commit -m "Updated image digest"
        git push -u origin master
   
    - name: Log in to OpenShift 
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{secrets.OPENSHIFT_SERVER}}
        openshift_token: ${{secrets.OPENSHIFT_TOKEN}}
        insecure_skip_tls_verify: true

    - name: Deploy gitops application in ArgoCD
      run: |
        cd sample-python-basic-gitops/argo
        oc apply -f application-staging.yaml -n openshift-gitops
